steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-f', 'Dockerfile-$PROJECT_ID', '-t', 'gcr.io/$PROJECT_ID/compute-gpu-monitoring:$SHORT_SHA', '-t',
            'gcr.io/$PROJECT_ID/compute-gpu-monitoring:latest', '.','--build-arg','DOCKER_REPO=gcr.io/$PROJECT_ID/vision' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/compute-gpu-monitoring:$SHORT_SHA']

images: ['gcr.io/$PROJECT_ID/compute-gpu-monitoring:$SHORT_SHA', 'gcr.io/$PROJECT_ID/compute-gpu-monitoring:latest']

timeout: 6000s